TryGhost/Ghost-Desktop

app/components/gh-instance-host.js, app/routes/application.js, app/templates/components/gh-instance-host.hbs, app/utils/window-menu.js, tests/unit/utils/window-menu-test.js
- Adds a basic window menu (shortcuts for individual blogs are still missing)
- Adds developer tools for blog instances
Ref #4, Closes #8
=> Add Window Menu, Add Developer Tools for Blog Instance

app/components/gh-instance-host.js, app/utils/window-menu.js
=> Handle WebView New-Window Event

.travis.yml, app/components/gh-add-blog.js, app/components/gh-app.js, app/components/gh-instance-host.js, app/components/gh-switcher.js, app/models/blog.js, app/routes/application.js, app/styles/app.css, app/styles/components/add-blog.css, app/templates/components/gh-add-blog.hbs, app/templates/components/gh-switcher.hbs, app/utils/context-menu.js, app/utils/get-blog-name.js, app/utils/window-menu.js, package.json, tests/integration/components/gh-add-blog-test.js, tests/integration/components/gh-app-test.js, tests/integration/components/gh-instance-host-test.js, tests/unit/utils/context-menu-test.js, tests/unit/utils/get-blog-name-test.js, tests/unit/utils/window-menu-test.js
=> Add automatic login

.github/PULL_REQUEST_TEMPLATE.md, app/components/gh-add-blog.js, app/templates/components/gh-add-blog.hbs, app/utils/sanitize-url.js, tests/unit/utils/sanitize-url-test.js
- The url input field is now smart enough to recognize and fix small
mistakes the user might make during input
- Also added a GitHub PR Template
=> Self-Heal Url

.gitignore, .travis.yml, Gruntfile.js, bower.json, package.json, scripts/log-coverage.js, testem.js, tests/blanket-options.js, tests/electron.js, tests/helpers/report-coverage.js, tests/index.html
- Enables coverage reports using a bunch of custom code and ember-cli-blanket
- Enables Travis to do coverage reports
- Enables Codecov
=> Coverage Reports

main/entry.js, main/squirrel.js, package.json
Got some code for us? Awesome 🎊!
Please include a description of your change & check your PR against this list, thanks!
More info can be found by clicking the "guidelines for contributing" link above.
=> Adding window state management

app/utils/context-menu.js, package.json, tests/unit/utils/context-menu-test.js
Less dependencies, more tests, more :tada:
=> Add Context Menu Test

app/routes/application.js, tests/unit/utils/window-menu-test.js
Includes the Window Menu in tests again.
=> Include Window Menu in Tests

main/preload.js
- Enables the context menu in Ghost instances
=> Enable Ghost Instance Context Menu

.eslintrc.json, app/components/gh-instance-host.js, app/utils/phrases.js, main/load-error/error.html, tests/integration/components/gh-instance-host-test.js, tests/unit/components/gh-instance-host-test.js
- If the page fails to load, we’re displaying a little error message
=> Handle Internet Loss

main/basic-update.js, main/entry.js
- Enables a basic update warning for the dev build
=> Enable Basic Update Warning for Dev

README.md
- Updated readme for dev release
=> Update Readme for Dev Release

app/components/gh-app.js, app/utils/set-dock-menu.js, tests/unit/utils/set-dock-menu-test.js
- Blogs are now in the dock menu, allowing people to switch to blogs
directly from the blog menu
Closes #60
=> Setup Dock Menu with Blogs

app/components/gh-edit-blog.js, app/models/blog.js, app/templates/components/gh-switcher.hbs, app/utils/color-picker.js, app/utils/get-blog-name.js, app/utils/get-is-ghost.js, package.json, tests/fixtures/blogs.js, tests/integration/components/gh-switcher-test.js, tests/unit/models/blog-test.js, tests/unit/utils/color-picker-test.js, tests/unit/utils/get-blog-name-test.js, tests/unit/utils/get-is-ghost-test.js
Adds a pleasantly colored blog icon to the switcher.
- [?] The build will pass (run `npm test`).
=> Adding colored icon. Closes #57

app/utils/inject-css.js, tests/unit/routes/application-test.js, tests/unit/utils/context-menu-test.js, tests/unit/utils/get-blog-name-test.js, tests/unit/utils/get-current-window-test.js, tests/unit/utils/get-is-ghost-test.js, tests/unit/utils/inject-css-test.js, tests/unit/utils/set-dock-menu-test.js, tests/unit/utils/set-user-tasks-test.js
We still have a few things uncovered, but this batch increases coverage of our utilities and the app route.
=> More Tests

.gitignore, app/components/gh-switcher.js, app/models/blog.js, app/utils/fetch-contributors.js, main/entry.js, tests/fixtures/contributor-response.js, tests/integration/components/gh-switcher-test.js, tests/unit/utils/fetch-contributors-test.js
- Enables the user to randomize a blogs icon color with a right click
=> Allow Change of Icon Color

app/components/gh-instance-host.js, app/models/blog.js, tests/fixtures/blogs.js, tests/unit/components/gh-instance-host-test.js, tests/unit/models/blog-test.js, tests/unit/utils/get-blog-name-test.js, tests/unit/utils/set-user-tasks-test.js
=> Update Blog Name if Changed

app/components/gh-app.js
=> HTML-Encode blog name in OS menus

.eslintrc.json, Gruntfile.js, main/entry.js, main/preload.js, main/squirrel.js, main/window-state.js, package.json
Uses the operating system's native spell checking features to spell check.
Closes #82
=> Add Spell Checking

app/services/auto-update.js
=> Ensure AutoUpdate respects Connection

Gruntfile.js, app/services/auto-update.js, app/templates/components/gh-preferences.hbs, docs/developer-environment.md, package.json, public/assets/inject/css/linux.css, tests/unit/services/auto-update-test.js
This PR adds support for Ubuntu.
Closes #105, #74
=> Ubuntu Support

app/components/gh-instance-host.js
Got some code for us? Awesome 🎊!
Please include a description of your change & check your PR against this list, thanks!
More info can be found by clicking the "guidelines for contributing" link above.
- from: https://github.com/electron/electron/blob/master/docs/tutorial/desktop-environment-integration.md#notifications-windows-linux-os-x
- The title is hardcoded to `Ghost Desktop` now. Does it need to be changed?
Signed-off-by: Kenneth Lim <kennethlimcp@gmail.com>
=> fix: proper notification data

Gruntfile.js
Adds a maintainer field, ensuring that Ubuntu users aren't annoyed by my Ubuntu incompetence.
Closes #124
=> Add Ubuntu Maintainer

app/components/gh-preferences.js, app/routes/application.js, app/services/preferences.js, app/styles/components/preferences.css, app/templates/components/gh-preferences.hbs, tests/integration/components/gh-preferences-test.js, tests/unit/routes/application-test.js, tests/unit/services/auto-update-test.js
Users will now be able to set a custom zoom, which we pass
over to the web-frame, where Chromium will use its native
magic to scale things properly.
Closes #122
=> Add Zoom Preference

app/models/blog.js
=> Delete Password during Blog Delete

app/services/auto-update.js, docs/creating-builds.md
=> Add Release Channel Capability

main/preload.js, main/preload/devtron.js, main/preload/spellchecker.js, package.json
=> Update Electron to 1.2.7

.jscsrc, app/components/gh-basic-auth.js, app/components/gh-edit-blog.js, app/components/gh-instance-host.js, app/models/blog.js, app/routes/application.js, app/styles/app.css, app/styles/components/edit-blog.css, app/styles/components/instance-host.css, app/styles/layouts/loading.css, app/templates/components/gh-basic-auth.hbs, app/templates/components/gh-edit-blog.hbs, app/templates/components/gh-instance-host.hbs, app/utils/get-is-ghost.js, app/utils/phrases.js, main/basic-auth.js, main/blog-data.js, main/entry.js, main/squirrel.js, package.json, tests/integration/components/gh-basic-auth-test.js, tests/integration/components/gh-dictionaries-dropdown-test.js, tests/integration/components/gh-instance-host-test.js, tests/unit/components/gh-instance-host-test.js
This commit adds support for basic authentication - and fixes
a few bugs along the way.
=> Implement Basic Authentication

app/components/gh-app.js, app/components/gh-find-in-webview.js, app/components/gh-instance-host.js, app/services/window-menu.js, app/styles/app.css, app/styles/components/app.css, app/styles/components/find-webview.css, app/styles/components/instance-host.css, app/templates/components/gh-app.hbs, app/templates/components/gh-find-in-webview.hbs, app/templates/components/gh-instance-host.hbs, tests/integration/components/gh-find-in-webview-test.js, tests/unit/components/gh-find-in-webview-test.js, tests/unit/routes/application-test.js
This commit adds features and tests for a basic "find in page" implementation. Before we can release this, we'll need to add some design.
=> Find in Page: Basic Implementation

app/components/gh-find-in-webview.js, app/styles/app.css, app/styles/components/power-select.css, app/templates/components/gh-find-in-webview.hbs, tests/integration/components/gh-find-in-webview-test.js, tests/unit/components/gh-find-in-webview-test.js, tests/unit/routes/application-test.js
=> Style CmdCtrl+F Find

app/components/gh-find-in-webview.js, app/components/gh-instance-host.js, app/initializers/services.js, app/services/webview-shortcuts.js, app/services/window-menu.js, app/utils/find-visible-webview.js, app/utils/window-menu.js, package.json, tests/fixtures/static-shortcuts/shortcuts.html, tests/unit/components/gh-find-in-webview-test.js, tests/unit/initializers/services-test.js, tests/unit/services/webview-shortcuts-test.js, tests/unit/utils/find-visible-webview-test.js
This commit adds keyboard shortcuts for the webview as well as a number of convenience methods to easily add shortcuts in the future.
Closes #192
=> Add fancy keyboard shortcuts

app/styles/components/app.css, app/styles/components/edit-blog.css, app/templates/components/gh-app.hbs
This PR is tiny, it just centers the `Add Blog` flow for better looks :art:
=> Center Add Blog

package.json
...just updating some of our dependencies ✨  📦
=> Electron 1.3.8, Ember-Electron 1.10

app/components/gh-instance-host.js, app/utils/escape-string.js, package.json, scripts/create-osx-build.js, tests/unit/utils/color-picker-test.js, tests/unit/utils/escape-string-test.js
We previously did not properly escape the credentials when passing them off to the blog. Jake Champion is the hero who alerted us to this fact - thanks, Jake!
(Also, this PR sneaks in a little build adjustment)
=> Escape Credentials

package.json
No biggie: Update to Electron 1.4.7.
=> Electron 1.4.7

.travis.yml
Our Travis images were a bit outdated - and the whole build is still not as stable as I'd like for it to be. This PR is basically WIP until Travis gives us  👍
=> Various Updates to Travis

app/utils/window-menu.js
Oh hey, a `maximize` button in the window menu, just for our Linux friends!
Closes #218 
Closes #193
=> Maximize button for linux

app/components/gh-edit-blog.js, app/utils/sanitize-url.js, tests/integration/components/gh-edit-blog-test.js, tests/unit/utils/sanitize-url-test.js
We previously didn't match a bunch of URLs that were really ought to be matched.
Closes #191
=> Improve our URL matching

app/components/gh-app.js, app/utils/get-blog-name.js
Trouble: The blog name isn't HTML-decoded, therefore non-ASCII blog names look weird. This fixes that.
Closes #244
=> HTML-Decode the blog name

.travis.yml, app/components/gh-instance-host.js, app/helpers/background-style.js, app/models/blog.js, app/services/preferences.js, app/templates/components/gh-instance-host.hbs, app/templates/components/gh-switcher.hbs, app/utils/get-blog-name.js, app/utils/get-is-ghost.js, app/utils/inject-css.js, tests/ember-electron/main.js, tests/integration/components/gh-find-in-webview-test.js, tests/unit/helpers/background-style-test.js, tests/unit/models/blog-test.js, tests/unit/routes/application-test.js, tests/unit/services/webview-shortcuts-test.js, tests/unit/utils/get-blog-name-test.js, tests/unit/utils/get-is-ghost-test.js
Tests were broken, this PR unbreaks them.
=> Fix all the tests

app/app.js, app/components/gh-preferences.js, app/services/auto-update.js, app/templates/components/gh-preferences.hbs, app/utils/is-reachable.js, ember-electron/main/app.js, ember-electron/main/ipc.js, ember-electron/main/open-url.js, ember-electron/main/state-manager.js, package.json
To ensure that we won't run into more auto-updater issues, this PR adds a manual updater check. This will bypass the normal connection check and just go for it.
=> Improve auto-updater, debugging

app/templates/components/gh-preferences.hbs, assets/mas/app-contents-info.plist, ember-electron/electron-forge-config.js, ember-electron/main/app.js, ember-electron/main/window-state.js, package.json
Hi,
I updated/extended the package/forge information for Debian to provide more detailed shortcut information in application menu.
Also, various copyright years have been amended to include 2017.
And last, I added missing dependency.
Took the liberty to bump Ghost Desktop to version 1.3.1 with those changes... ;-)
I checked the issue tracker but didn't find entries related to those changes. If necessary to have an issue for each, let me know and I'll create them for reference.
Regards, JoKi
=> Updated package information for Linux platform

app/utils/get-is-ghost.js, app/utils/is-reachable.js
This small PR ensures that we'll find all kinds of Ghost Admin pages.
Closes https://github.com/TryGhost/Ghost-Desktop/issues/308
=> fix: Harden is-reachable & get-is-ghost
