app/components/gh-switcher.js, app/helpers/switch-shortcut.js, app/templates/components/gh-switcher.hbs, tests/integration/components/gh-add-blog-test.js, tests/integration/components/gh-switcher-test.js, tests/unit/helpers/switch-shortcut-test.js
- Adds “quick switch” functionality, enabling users to switch back and forth between blogs by using Ctrl / Cmd and the index (starting from 1)
Closes #4
=> Setup Quick Switch Shortcuts

app/components/gh-app.js
Fixes #65 ! For whatever reason, the computed property wasn't getting updated when the `blogs` property was set to an empty list. Making it a simple computed property getter fixes the issue.
Please include a description of your change & check your PR against this list, thanks!
More info can be found by clicking the "guidelines for contributing" link above.
=> Fixes a cosmetic issue where removing all blogs presents the user with a blank screen.

app/templates/components/gh-instance-host.hbs
Fixes #66 by disabling web security (thus enabling http/https content mixing) on the guest webview.
=> Disables web security on the guest webview to prevent mixed content errors.

main/entry.js
Fixes #79 by preventing navigation from the main app window.
=> Preventing navigation away from the app window when dropping content.

app/models/blog.js, app/utils/color-picker.js, app/utils/set-window-title.js, package.json, tests/unit/models/blog-test.js, tests/unit/utils/color-picker-test.js, tests/unit/utils/set-window-title-test.js
Fixes #85 
- Added a html entity decoding library.
- Using it to decode the title string, and setting it.
- Modified the existing setWindowTitle test.
=> Decodes html entities in window title

main/entry.js, main/window-state.js
This should fix #83, and cleans up entry.js a bit.
=> Window position and size respects available screen real estate.

app/components/gh-app.js, app/utils/get-current-window.js, app/utils/set-user-tasks.js
* Restricts Ghost Desktop to one instance
* Switches to the blog selected in the user tasks list
* Restores and focuses window (if required)
fixes #61
=> Adds user tasks (fixes #61)

.travis.yml, Gruntfile.js, app/components/gh-app.js, app/components/gh-preferences.js, app/components/gh-switcher.js, app/routes/application.js, app/services/auto-update.js, app/services/window-menu.js, app/templates/components/gh-preferences.hbs, app/utils/window-menu.js, main/entry.js, main/squirrel.js, package.json, tests/fixtures/auto-update.js, tests/unit/components/gh-preferences-test.js, tests/unit/routes/application-test.js, tests/unit/services/auto-update-test.js, tests/unit/utils/window-menu-test.js
* Adds an auto updater service (which currently works on OS X), which is able to fetch new versions of the app and update itself. The service is correctly configured, but our dev builds are not code signed - the app will therefore refuse to update to them.
* Adds a window menu service, allowing other ember components to call the service to change the window menu. This allows us to update on Cmd+Q. It also allows us to localize the blog shortcuts (bugfix) and to have the blogs in the window menu, under view.
* Minor bugfixes and changes in the app's entry logic.
=> Auto Updater (OS X)

app/models/blog.js, app/utils/require-keytar.js, tests/unit/utils/require-keytar-test.js
* Wraps the keytar require in a try/catch. If it throws then return false, otherwise return the module.
* On setPassword return false if keytar fails
* On getPassword return null if keytar fails
(fixes #58)
=> Continue if keytar fails

app/components/gh-switcher.js, app/services/window-menu.js, app/styles/components/switcher.css, app/templates/components/gh-switcher.hbs, app/utils/window-menu.js, tests/integration/components/gh-switcher-test.js, tests/unit/components/gh-switcher-test.js, tests/unit/utils/window-menu-test.js
Removes the preferences button from the switcher, adds it to Ghost Desktop's Application menu (Apple), and to the File menu (Windows, Linux). Fixes #96
=> Adding preferences pane to menu bar

docs/developer-environment.md
Added -32 or -64 to build-native-deps in docs.  See #97 
- [x ] Commit message has a short title & issue references
- [x ] Commits are squashed 
- [x ] The build will pass (run `npm test`).
More info can be found by clicking the "guidelines for contributing" link above.
=> fix build-native-deps command in docs

main/preload.js, public/assets/inject/css/all.css
We're using a little CSS hack to get an event as soon as a link is added - once done, we ensure that it is opened externally, if it is indeed an external link.
Closes #131
=> Ensure links open externally

ember-cli-build.js
Fixing an odd Node 6 issue in which ember cli complains about isProduction not being defined. I suspect this may have something to do with variable declaration order.
=> Fixing build issue on Node 6

package.json
Both `keytar` and `spellchecker` require native builds, so remove the explicit `-w keytar` parameter to allow any module to be built.
Closes #154
=> Remove -w keytar so spellchecker is included

main/preload.js, main/preload/upgrade-notification.js
Changing the ghost core upgrade notification text to be a lil bit more clear about what it is you need to upgrade. Fixes(?) #167 
@felixrieseberg, @ErisDS let me know if either of you think there's a better way to message this 😅
=> Changing the upgrade notification text

main/preload/spellchecker.js
We can’t really fix how the spellchecker works, but we can fix *when*
it works. This is a poor man’s solution to our original problem (pastes
taking too much time) - whenever text is pasted into the textarea, we
briefly disable the spellchecker, just to re-enable it a few moments
later.
Closes #168
=> Slightly improve paste performance

README.md
- makes it more obvious that Ghost Desktop is only intended to work with Ghost :smile:
=> :memo: add link back to main Ghost repository

app/index.html, app/styles/layouts/loading.css, app/styles/patterns/global.css, main/load-error/error.html
Based on an increasingly popular trend and modern web typography capabilities, switch out Google Fonts for default native system fonts, tailored in a stack to suit every device. Also makes some very minor visual adjustments to suit.
Nixes all references to Google Fonts, and provides a faster rendering experience and fewer http requests. 💃 
Reference material:
- https://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/
- https://medium.design/system-shock-6b1dc6d6596f#.rhqx5fmyz
Dependencies:
- https://github.com/TryGhost/Ghost-Admin/pull/211
- https://github.com/TryGhost/Ghost/pull/7219
- https://github.com/TryGhost/Ghost-Desktop/pull/190
=> Switch to new native system font stack

app/components/gh-app.js, app/components/gh-edit-blog.js, app/components/gh-instance-host.js, app/models/blog.js, app/styles/components/edit-blog.css, app/templates/components/gh-app.hbs, app/templates/components/gh-edit-blog.hbs, main/preload/check-login.js
Previously, when the password was incorrect, we didn't really handle things all that well - we displayed the individual blog's login page, but did not actually capture a newly entered password. Now, we detect the login error, display the 'edit blog' modal and retry as soon as the user has hit 'save' again.
=> Handle changed password gracefully

app/styles/components/instance-host.css, package.json
We previously didn't upgrade to Electron 1.4 right away, because we had some trouble with webviews unloading in unpredictable ways - this is now fixed, so we can enjoy the 1.4-goodness.
=> Electron 1.4

Gruntfile.js, assets/mas/app-contents-info.plist, assets/mas/app-store-child.plist, assets/mas/app-store-parent.plist, assets/mas/helper-contents-info.plist, package.json, scripts/create-mas-build.js
This PR enables us to make Mac App Store builds :package:. It also moves many Grunt tasks into npm.
=> Mac App Store Builds

app/components/gh-app.js, app/components/gh-switcher.js, app/styles/components/app.css, app/styles/components/edit-blog.css, app/styles/components/find-webview.css, app/styles/components/instance-host.css, app/styles/components/preferences.css, app/styles/components/switcher.css, app/utils/versions.js, main/entry.js, tests/unit/utils/versions-test.js
Look at this hot beauty. Electron 1.4.7 (separate PR is open) introduced the ability to mark `BrowserWindows` as `vibrant`, using the native macOS `NSVisualEffectView` vibrancy available from Yosemite onwards. It's quite pretty :art:
=> Make window “vibrant” (Yosemite and up only)

app/components/gh-app.js, app/services/webview-shortcuts.js
Previously, the webview-shortcuts would just attempt to fire. If the webview wasn't ready, nothing would happen.
This PR updates the API, enabling the shortcuts to wait for the webview to load. 
Ref #227
=> Shortcuts can now wait for webview

app/components/gh-app.js, app/services/window-menu.js, app/styles/components/switcher.css, docs/deeplinks.md, main/open-url.js
This enables the `ghost://open-blog` deep link to prefill not just the url field, but also the user field.
=> Prefill user field from `open-blog`

app/components/gh-switcher.js, app/models/blog.js, app/styles/components/switcher.css, app/templates/components/gh-switcher.hbs, package.json
This PR enables the "sorting" of blogs, meaning that you can drag them around in the switcher. All references and shortcuts will automatically be updated. The macOS dock icon is a notable exception (the order there isn't updated), but I believe that to be just fine :wink:
Closes #237
=> Allow sorting of blogs

app/utils/window-menu.js, main/app.js, main/ipc.js
Vibrancy (that cool transparency effect on macOS) is lost if the window is reloaded. This is a bug in Electron, but we can work around it by re-creating the browserWindow once a reload is requested.
Closes #242
=> Retain vibrancy after refresh

main/app.js
Sadness: On Windows, we manage to close the window, but the app seems to stick around. This is an attempt to fix that.
Ref #239
=> Close app when all windows closed

ember-electron/main/app.js, ember-electron/main/window-state.js
Hi,
Although the main window itself is resizable but the values of minHeight and minWidth should be reviewed. I'm currently running Ghost Desktop on 1280x800 resolution. Also, a lot of laptops have a native screen resolution of 1366x768 which wouldn't provide enough real-estate to display the Ghost Desktop properly.
Adjusted minimum height down to 720px instead of 800px.
See also [Linux: Main Window not resizable #284](https://github.com/TryGhost/Ghost-Desktop/issues/284)
=> adjust minimum height to lower screen resolution

app/services/window-menu.js
Hi @felixrieseberg 
Referring to #289 you said it has been fixed. Unfortunately, it has not been fixed completely in 1.4.0.
- Content ==> Stories
And some minor capitalisation was still lingering around. This PR puts all menu labels under "View" in sync with the navigation in Ghost Admin. 
Hope that's okay. Cheers, JoKi
=> Sync view menu with Ghost admin

ember-electron/main/app.js
Hi @felixrieseberg 
Eventually, this PR might take care of the following issues: #239 and #251 
I already commented it here: https://github.com/TryGhost/Ghost-Desktop/issues/239#issuecomment-322464549
We had similar issues in one of our Electron apps, and using these two code blocks helped to resolve the problem of proper window close and release across Windows, Linux and macOS.
It seems that the behaviour of Ghost Desktop on Windows has been improved already and the `Electron` process(es) are terminated as expected. Eventually, you shall ignore this PR but consider to close the referenced issues.
Please let me know what you think about that.
Thanks and regards, JoKi
=> Improve window handling (release and close)

app/services/window-menu.js
Hi @felixrieseberg 
I just discovered that two menu entries under View have the same hotkey combination:
- Team
- Tags
I took the liberty to change `Team` to `CtrlOrCmd+Alt+E`, as the other letters in `Tags` are already in use. Hope that's okay for everyone.
Cheers, JoKi
=> Change duplicate hotkey (Team vs Tags)

app/components/gh-preferences.js, app/templates/components/gh-preferences.hbs
We're going to temporarily hide the spellchecker configuration until Ghost Admin becomes spellchecker-aware again.
Closes https://github.com/TryGhost/Ghost-Desktop/issues/307
=> fix: Hide spellchecker configuration
